return {
--     "saghen/blink.cmp",
--     dependencies = {
--         {
--             "rafamadriz/friendly-snippets",
--             "supermaven-inc/supermaven-nvim",
--             "huijiro/blink-cmp-supermaven",
--         },
--     },
--
--     version = "1.*",
--     ---@module 'blink.cmp'
--     ---@type blink.cmp.Config
--     opts = {
--         keymap = {
--             preset = "none",
--             ["<Up>"] = { "select_prev", "fallback" },
--             ["<Down>"] = { "select_next", "fallback" },
--             ["<Tab>"] = { "accept", "fallback" }, -- show with a list of providers
--             ["<C-space>"] = {
--                 function(cmp)
--                     cmp.show()
--                 end,
--             },
--         },
--         appearance = {
--             nerd_font_variant = "mono",
--         },
--         completion = {
--             documentation = { auto_show = false },
--             menu = {
--                 -- Don't automatically show the completion menu
--                 auto_show = true,
--             },
--             ghost_text = { enabled = true },
--             trigger = {
--                 prefetch_on_insert = false,
--                 show_in_snippet =false,
--                 show_on_backspace = false,
--                 show_on_backspace_in_keyword =false,
--                 show_on_insert = false,
--             },
--         },
--
--         sources = {
--             default = { "lsp", "supermaven", "path", "snippets", "buffer" },
--             providers = {
--                 supermaven = {
--                     name = "supermaven",
--                     module = "blink-cmp-supermaven",
--                     async = true,
--                 },
--             },
--         },
--         fuzzy = { implementation = "prefer_rust_with_warning" },
}
